# Generated by Django 4.1 on 2022-09-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_author_order_publisher_shippingaddress_review_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
